-- simSkel lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simSkel=require('simSkel')

__initFunctions=__initFunctions or {}
table.insert(__initFunctions, function()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simSkel'][funcName]=wrapperGenerator(_G['simSkel'][funcName])
    end

end)

return simSkel
