# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from braccio_controller/coords.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class coords(genpy.Message):
  _md5sum = "865536847ef9cce2f44ef34a4baed036"
  _type = "braccio_controller/coords"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 x
int16 y
int16 z
int8 angle
int8 wrist
bool real
uint8 gripper"""
  __slots__ = ['x','y','z','angle','wrist','real','gripper']
  _slot_types = ['int16','int16','int16','int8','int8','bool','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,angle,wrist,real,gripper

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(coords, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.z is None:
        self.z = 0
      if self.angle is None:
        self.angle = 0
      if self.wrist is None:
        self.wrist = 0
      if self.real is None:
        self.real = False
      if self.gripper is None:
        self.gripper = 0
    else:
      self.x = 0
      self.y = 0
      self.z = 0
      self.angle = 0
      self.wrist = 0
      self.real = False
      self.gripper = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3h2b2B().pack(_x.x, _x.y, _x.z, _x.angle, _x.wrist, _x.real, _x.gripper))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.x, _x.y, _x.z, _x.angle, _x.wrist, _x.real, _x.gripper,) = _get_struct_3h2b2B().unpack(str[start:end])
      self.real = bool(self.real)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3h2b2B().pack(_x.x, _x.y, _x.z, _x.angle, _x.wrist, _x.real, _x.gripper))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.x, _x.y, _x.z, _x.angle, _x.wrist, _x.real, _x.gripper,) = _get_struct_3h2b2B().unpack(str[start:end])
      self.real = bool(self.real)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3h2b2B = None
def _get_struct_3h2b2B():
    global _struct_3h2b2B
    if _struct_3h2b2B is None:
        _struct_3h2b2B = struct.Struct("<3h2b2B")
    return _struct_3h2b2B
